### ISSUE TITLE
how can I use the "-target=resource" feature of terraform command with this resource in a pipeline?

### ISSUE THREAD

**Issue by vipinable** [ljfranklin/terraform-resource#112]

**Comment by ljfranklin** [comment]
The resource doesn't support use of the `-target` flag. According to the [Terraform docs](https://www.terraform.io/docs/commands/plan.html#resource-targeting) that flag is only intended to be used in exceptional circumstances to unwedge a deployment, using it in your pipeline seems like an anti-pattern. The docs suggest breaking your configuration down into smaller pieces that can be applied individually, I'd give that a try rather than relying on the `-target` flag.

**Comment by vipinable** [comment]
Make sense. I missed the details of that option. Regular use may cause inconsistencies.
