### ISSUE TITLE
Support 'refresh' operation

### ISSUE THREAD

**Issue by derjust** [ljfranklin/terraform-resource#141]
We use the Terraform resource type to manage all our infrastructure.
While it works great to _create_ infrastructure, the `destroy` part causes some trouble.

In the end, all those issues relate around the fact that (yet) Terraform doesn't refresh its data sources during a `destroy`.
While is addressed in [v0.15](https://github.com/hashicorp/terraform/releases/tag/v0.15.0-alpha20210210) eventually, almost all workarounds to this require the use of `refresh`.
For example around EKS:
* https://github.com/hashicorp/terraform/issues/27172
* https://github.com/hashicorp/terraform-provider-kubernetes/issues/1131#issuecomment-776326103

It would be great to have - like `plan_only` - an option to let the Terraform resource refresh all it's date, and update the remote state if configured.

**Comment by ljfranklin** [comment]
I'd rather not add a workaround to the resource when the underlying issue is already fixed in the next Terraform version. As a temporary workaround, could you add a `put: terraform` step just before the destroy step? That way the `terraform apply` will refresh the state just before the destroy action.

Alternatively you can try temporarily running the destroy step with the `ljfranklin/terraform-resource:rc` image which contains the latest Terraform 0.15 alpha. Note that the RC images don't run through my CI pipeline, there's a chance the resource will need updated to be compatible with Terraform 0.15.
