### ISSUE TITLE
Unable to pass gcp json to tf plan

### ISSUE THREAD

**Issue by ralphpi** [ljfranklin/terraform-resource#144]
There doesn't seem to be easy way to allow json content provided in credentials for the GCS to also be used to run as the terraform creds for GCP using `$GOOGLE_APPLICATION_CREDENTIAL`  being that its expecting a file. I also believe the gcs bucket backend isnt working properly. With the current setup below I keep getting returned 

`open gce-subnet-test-repo/path/to/tf/files/testing/resource_backend_override.tf: no such file or directory`

```resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
- name: gce-subnet-test-repo
  type: git
  source:
    uri: https://test.com/scm/tf-gcp/networks.git
    branch: master
    private_key: ((private-repo-key))
- name: terraform
  type: terraform
  source:
    env_name: development
    backend_type: gcs
    backend_config:
      bucket: saas-terraform
      prefix: dev/networks/us-east4/subnets/test/state
      credentials: ((gcp-json-key))
    env:
       GOOGLE_APPLICATION_CREDENTIALS: ((gcp-json-key))
       GCP_JSON_KEY: ((gcp-json-key))
    vars:
      env: dev
jobs:
- name: terraform-plan
  plan:
  - get: gce-subnet-test-repo
  - task: gcp-auth
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: alpine}
      outputs:
        - name: creds
      run:
        path: /bin/sh
        args:
          - -cx
          - |
            echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/build/cred.json
  - put: terraform
    params:
      env_name: development
      terraform_source: gce-subnet-test-repo/networks/envs/dev/us-east4/testing
      plan_only: true

**Comment by ljfranklin** [comment]
For the backend config, set `credentials` to the JSON contents rather than a path. The docs don't say it explicitly, but that key accepts a [path or the contents of the file](https://github.com/hashicorp/terraform/blob/e9c7f37b8ca9391e8c5c6003da1067c704d530da/backend/remote-state/gcs/backend.go#L155-L156). Similarly the GCP provider itself accepts a JSON string as either an explicit `credentials` value in the provider config or any of [these env vars](https://github.com/hashicorp/terraform-provider-google/blob/ece9fdcc646589729ad21e04cfd7b90442e15e37/google/provider.go#L29-L31), but not `GOOGLE_APPLICATION_CREDENTIALS`.

But the actual error message, `open gce-subnet-test-repo/path/to/tf/files/testing/resource_backend_override.tf: no such file or directory`, it sounds like the directory `path/to/tf/files/testing` doesn't exist in your git repo. I would double-check that directory exists and try again. If you need to troubleshoot further you can try running `fly intercept` to SSH into the job container and look around at the files directly.

**Comment by ljfranklin** [comment]
Also `ourcelan_only` should be `plan_only`, hopefully just a typo when you pasted in the example

**Comment by ralphpi** [comment]
Sorry yeah copy paste typo. Im not to worried about the `GOOGLE_APPLICATION_CREDENTIALS` since im building the file in the task and setting `env:GOOGLE_APPLICATION_CREDENTIALS` value to that path (Winging that part, not sure if thats the right thing to do).   I updated git uri and terraform source to real value for more clarity. I must be doing something wrong with the `terraform_source`

**Comment by ralphpi** [comment]
Closing non-issue, using in correct paths for ref built cred file.
