### ISSUE TITLE
Accessing local files

### ISSUE THREAD

**Issue by UED094** [ljfranklin/terraform-resource#166]
I am trying to save some data into a local file but in concourse I am not able to see that output. When I output that folder and input terraform am only able to see metadata and name. Is there some other way to receive my local file ? Thank you so much for this great repo.

**Comment by ljfranklin** [comment]
I'm afraid this is an intentional limitation of resources in Concourse, any `put` step must persist all its outputs somewhere outside the container. If the data is very small you can add it directly as a Terraform output field and it will be present in a `terraform/metadata` file after `put: terraform` runs. For larger files you'll have to persist the data using a Terraform resource like S3 or GCS.

**Comment by UED094** [comment]
Thank you so much for quick response, I really appreciate that 👍  I will keep my solution in that structure.
