### ISSUE TITLE
Support specifying multiple var_file's

### ISSUE THREAD

**Issue by analytically** [ljfranklin/terraform-resource#29]
https://www.terraform.io/intro/getting-started/variables.html

"You can use multiple -var-file arguments in a single command, with some checked in to version control and others not checked in."

**Comment by ljfranklin** [comment]
@analytically yeah, that was an oversight on my part not making that field an array from the beginning. I'll add a new `var_files` field and deprecate the old `var_file` field sometime in the next week.

**Comment by ljfranklin** [comment]
@analytically the `var_files` feature should now be present in the `latest` image. Closing this out!

**Comment by analytically** [comment]
Can't seem to make it with with a tfvars file:

```
environment = "dev"
region = "us-west-2"
```

2017/03/19 10:29:08 Failed to parse `terraform.var_files`: Failed to parse TerraformVarFile at '/tmp/build/put/test/terraform/env-dev-us-west-2/terraform.tfvars': yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `environ...` into map[string]interface {}

**Comment by analytically** [comment]
`If a terraform.tfvars file is present in the current directory, Terraform automatically loads it to populate variables. If the file is named something else, you can use the -var-file flag directly to specify a file. These files are the same syntax as Terraform configuration files. And like Terraform configuration files, these files can also be JSON.`

**Comment by ljfranklin** [comment]
@analytically to make this resource integrate more easily with the rest of the Concourse ecosystem, I opted to support `var_files` as YAML or JSON rather than Hashicorp's homerolled HCL format. The name is a bit misleading as the resource doesn't actually pass those files directly via the `var-file` Terraform flag. Feel free to re-open if you have a strong use case for supporting HCL, but for now you'll need to use YAML or JSON.
