### ISSUE TITLE
Support terraform init

### ISSUE THREAD

**Issue by analytically** [ljfranklin/terraform-resource#30]
In 0.9, remote state backends has changed. 

```
Backend reinitialization required. Please run "terraform init".
Reason: Initial configuration of the requested backend "s3"

The "backend" is the interface that Terraform uses to store state,
perform operations, etc. If this message is showing up, it means that the
Terraform configuration you're using is using a custom configuration for
the Terraform backend.

Changes to backend configurations require reinitialization. This allows
Terraform to setup the new configuration, copy existing state, etc. This is
only done during "terraform init". Please run that command now then try again.

If the change reason above is incorrect, please verify your configuration
hasn't changed and try again. At this point, no changes to your existing
configuration or state have been made.
```

**Comment by ljfranklin** [comment]
@analytically unfortunately this resource can't use the built-in remote state backends at all right now.  Concourse resources are required to implement a `check` function that can look for new versions of a resource. To have tighter control over the state files, the resource currently supports [only S3](https://github.com/ljfranklin/terraform-resource#source-configuration). However, now that backends are listed directly in the Terraform config files it becomes even more desirable to support all the backends. I'll have to do some more thinking on this.

Out of curiosity, would you use any backends other than S3?

**Comment by analytically** [comment]
I'm just using S3.

**Comment by ljfranklin** [comment]
Opened a Concourse issue [here](https://github.com/concourse/concourse/issues/977) to see if the Concourse team has any ideas for a nice implementation around supporting state backends.

Also if anyone has a strong need for backend support other than the current S3 support this resource provides, please leave a comment 👍

**Comment by Seraf** [comment]
Hello,

That's gonna be a mandatory change to run it automatically before any terraform command because of : https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0100-beta1-unreleased

**Comment by ljfranklin** [comment]
@Seraf thanks for the heads up, I'll start looking into how to handle that breaking change. Definitely agree that adding a runtime dependency on Terraform's servers isn't great. Baking the providers into the docker image and rebuilding on a daily timer or similar doesn't seem too bad.

**Comment by Seraf** [comment]
@ljfranklin, I thought a little bit about it, I'm not sure that a docker image with providers will be enough : because of the version constraint in configuration, the providers will be setup in the local `.terraform` folder.
It also that means that each project using different providers should have their own terraform image. Sounds a bit complicated to maintain in the long run.
But anyway, I think it's the same deal than `npm`, `composer`, `bundle` and all these libraries manager, it needs some "cache" from concourse itself.

Also, there was a new update about the apply feature : https://github.com/hashicorp/terraform/blob/master/website/upgrade-guides/0-10.html.markdown#interactive-approval-in-terraform-apply

It will be a breaking change for the way terraform is used by the terraform resource, so it needs to be handled before switching to the 0.10 version

**Comment by ljfranklin** [comment]
Here's a branch with the [0.10 changes](https://github.com/ljfranklin/terraform-resource/tree/WIP-tf-0.10.0). This calls `init` before running other CLI commands in order to download the providers. Will merge after the Terraform team officially releases 0.10.

@Seraf after looking at the provider distribution more closely, it does seem difficult to cache all the providers in the docker image. I'm leaning towards no caching for now and we'll see if anyone has reliability issues when fetching providers from the Hashicorp servers.

@analytically even though the resource now runs `init`, it still won't support the built-in state backends just yet. Still on my radar though.

**Comment by ljfranklin** [comment]
The latest image now includes Terraform v0.10.0 which makes calling `init` mandatory. Spinning out a separate issue for supporting remote state backends: https://github.com/ljfranklin/terraform-resource/issues/39.
