### ISSUE TITLE
Why not embed the Terraform binary?

### ISSUE THREAD

**Issue by itsdalmo** [ljfranklin/terraform-resource#42]
Hi, first of all thank you for the great work on this resource :) 

After looking at this resource and other Concourse resources, I'm curious why you couldn't (or decided not to) embed the terraform binary and write bash scripts for in/out/check, as is done for e.g. the git resource?

**Comment by ljfranklin** [comment]
The Terraform binary is embedded in the resource Docker image, all the Go code is just orchestration around shelling out to the Terraform CLI.

As to why I chose Go instead of Bash, writing large scripts in Bash tends to be a maintenance nightmare. Bash can be tempting when the resource is simple, but seems like they often balloon up in complexity. The Concourse team has felt the pain on this and has already rewritten several of their Bash resources into Go.

Gonna close this out, but re-open if that doesn't answer it. Good question!

**Comment by itsdalmo** [comment]
Thanks for the informative answer :)
