### ISSUE TITLE
Support instance_profile on AWS

### ISSUE THREAD

**Issue by ThinkBriK** [ljfranklin/terraform-resource#63]
Hi !

For security reasons we like to get rid of static configuration tokens in concourse pipelines.
Do you plan on supporting AWS instance profile (https://aws.amazon.com/blogs/security/granting-permission-to-launch-ec2-instances-with-iam-roles-passrole-permission/) ?

**Comment by ljfranklin** [comment]
Try the [backend-beta image](https://github.com/ljfranklin/terraform-resource/tree/WIP-tf-backends#backend-beta) of the resource which supports the first-class Terraform state storage feature rather than my home-rolled S3 storage client. The Terraform [docs](https://www.terraform.io/docs/backends/types/s3.html#running-terraform-in-amazon-ec2) indicate that IAM profiles are supported. The only limitation of the backend image right now is the "plan" feature is missing due to a limitation in Terraform, otherwise the backend image should be functionally equivalent to the `latest` image.

**Comment by ThinkBriK** [comment]
Hi,

I tried your solution and got :

> 2018/08/14 12:29:55 Missing fields: 'storage.access_key_id', 'storage.secret_access_key'

**Comment by ljfranklin** [comment]
Make sure your pipeline config looks similar to https://github.com/ljfranklin/terraform-resource/tree/WIP-tf-backends#source-example, including `tag: backend-beta`. If you have an existing pool of environments, you can use the `migrated_from_storage` field: https://github.com/ljfranklin/terraform-resource/tree/WIP-tf-backends#migration-example. If those examples don't help, you can paste your redacted pipeline config into this issue.

**Comment by dvianello** [comment]
@ljfranklin, also looking into switching to instance profiles, but very aware that doing an `apply` without a `plan` on `prod` environment would be a very easy way to screw up. 

If there any way that with the backend resource we can `plan`, not persist the plan in s3 but maybe just pass it over to the `apply` step as an output/input, and then apply, all without using API keys? 

Or is the functionality completely broken?

**Comment by ThinkBriK** [comment]
@ljfranklin : thank you I was still using the deprecated _storage_ construct.
