### ISSUE TITLE
env_name is REQUIRED

### ISSUE THREAD

**Issue by eedwards-sk** [ljfranklin/terraform-resource#70]
documentation is incorrect

>2018/10/26 21:27:49 Must specify `put.params.env_name`, `put.params.env_name_file`, or `put.params.generate_random_name`

Why is this required? I DO NOT WANT TO USE ENVIRONMENTS

**Comment by eedwards-sk** [comment]
Also, they're not even environments any more, they're [workspaces](https://www.terraform.io/docs/state/workspaces.html)

**Comment by eedwards-sk** [comment]
https://github.com/ljfranklin/terraform-resource/blob/91574b7ab1d04964bbe560d5d61c525c44461117/src/terraform-resource/out/out.go#L196-L198

**Comment by ljfranklin** [comment]
Let's give the caps lock a break :) This resource has existed since early 2016, well before Terraform environments or workspaces existed. The resources used `env_name` as an ID for a state file that the resource stored in S3 using a custom S3 client. Once Terraform added workspaces, I switched from using a the S3 client to using Terraform workspaces and backends (see [backend-beta](https://github.com/ljfranklin/terraform-resource/tree/WIP-tf-backends#backend-beta)). The `env_name` key remains, only now it's used to create a workspace with that name. So the `env_name` field is required.

**Comment by eedwards-sk** [comment]
Workspaces are not required, and are often a bad idea. Maybe you could update the docs instead of knee jerk closing the issue because you don't like seeing capital letters?

Thanks for open sourcing it though, I'll fork it and fix it myself. :)

**Comment by eedwards-sk** [comment]
Apologies for being rude, I had a long week that culminated in this issue, and the response was inappropriate on my part. Your contributions to the concourse community are greatly appreciated.

This is a useful resource, but the forced use of environments/workspaces means it conflicts with my use case, which requires a clean state file that specifies no environment or workspace other than the 'default'.

It was frustrating after doing research over multiple available resources, and concluding that this was the most feature-complete and maintained resource, to discover that the one requirement I had was documented incorrectly.

I hope you can understand from that perspective where it would be appreciated if the docs reflected that it's not an optional field, and thus environments will be created in the state file.

**Comment by ljfranklin** [comment]
No worries, it happens. I expect setting `env_name: default` would work. Does that solve your use case?

**Comment by eedwards-sk** [comment]
Possibly! My primary concern is to be able to pull down the S3 files and run commands against them 'manually'. if needed, without needing to know or specify an environment name.

I also need the ability to 'plan', so the new backends won't fit my use case either.
