### ISSUE TITLE
self signed certificates for storage source

### ISSUE THREAD

**Issue by vchrisb** [ljfranklin/terraform-resource#73]
It would be great if this resource would support `skip_ssl_verification`, like e.g. the s3 resource, for connecting to a s3 compatible endpoint.

**Comment by ljfranklin** [comment]
@vchrisb I've got a [backend-beta](https://github.com/ljfranklin/terraform-resource/tree/WIP-tf-backends#backend-beta) image which uses the built-in Terraform backends to store statefiles rather than my homerolled S3 client. This backend supports a lot more options: https://www.terraform.io/docs/backends/types/s3.html#configuration-variables. That said, I'd encourage you to not skip SSL validation. Instead, Concourse provides a way to pass trusted CA certs into resource containers: https://github.com/concourse/concourse/issues/1027#issuecomment-344730600.

Going to close this out as `won't fix` but happy to continue the conversation if you have more questions.
