### ISSUE TITLE
migrate_from_storage does not work

### ISSUE THREAD

**Issue by saedalavinia** [ljfranklin/terraform-resource#79]
It doesn't seem like the instruction on migrate_from_storage is working. 

When I update my code and added backend_type and backend_config, the terraform PUT attempts to recreate the resources (for example, s3, route53, etc) and fails because it already exists.

**Comment by ljfranklin** [comment]
Whoops, I somehow manage to consistently write `migrate_from_storage` everywhere in the README when it should be `migrated_from_storage` (note the extra `d`). :man_facepalming: The README is now fixed, thanks for the heads up! Try adding the `d` and let me know if it works now.

**Comment by saedalavinia** [comment]
Thanks for the quick fix. 
Now on the next question, has this been tested with `env_name` ? 

My migration failing with: 
```sh
2019/03/25 14:19:53 Apply Error: Error running `workspace new -state`: exit status 1, Output: Workspace "domain" already exists
```

**Comment by ljfranklin** [comment]
@saedalavinia I suspect your initial `put` with the typoed `migrate_from_storage` created a new statefile in the newly configured backend. That first `apply` probably failed to create any resources since they already exist so the new statefile is most likely empty (although you should check). If that new statefile in the backend is empty you can fix the problem by manually deleting the new statefile and re-running your CI job. It should successfully migrate the statefile from the old S3 storage into your new backend.

**Comment by saedalavinia** [comment]
Oh that was an obvious one! :joy: 
I had initially done that .. but totally forgot that I retried with a few things before your answer! 

Thanks for your quick response!
