### ISSUE TITLE
Can the terraform outputs be printed as JSON?

### ISSUE THREAD

**Issue by aditya87** [ljfranklin/terraform-resource#8]
When we do a put to the resource in order to apply, the outputs we get are printed in the UI as HCL. It would be cool to have an option to print them as JSON, since we obviously consume them as JSON in CI. We could then just copy them from the concourse UI when we are trying to manually test our newly terraformed resources (rather than using subsequent CI jobs to do so).

**Comment by ljfranklin** [comment]
@aditya87 the green Outputs section is part of the streaming stdout from running `terraform apply` and that command doesn't currently support a `--json` flag. Feels a bit weird to print it a second time in the same task output in a different format.

Rather than adding additional output to `put`, which is already a bit noisy, you could add a second task that `cat`s the `metadata` file for human consumption. Here's an inline example: https://github.com/ljfranklin/terraform-resource/blob/94157d0b66ab6912f2a4cc5dee94cba93969020a/ci/pipeline.yml#L59-L75.

If you frequently need to manually use a Terraformed environment, you could use the terraform output as a lock file: https://github.com/ljfranklin/terraform-resource/blob/94157d0b66ab6912f2a4cc5dee94cba93969020a/ci/pipeline.yml#L125-L140. This way you can manually claim an environment, do some testing, then release it.

**Comment by ljfranklin** [comment]
Closing this out, but feel free to re-open if the suggestions mentioned above don't work out.
