### ISSUE TITLE
Unable to create state bucket using resource

### ISSUE THREAD

**Issue by DanielJonesEB** [ljfranklin/terraform-resource#87]
Hi! Many thanks for the resource, we use it heavily.

With the old state management, there was a nice trick where you could bootstrap a project using Terraform - so you could create the bucket that you'd store state in (and any things it depends on) as the first job in your pipeline, and because state was only persisted _after_ Terraform had run, it wouldn't notice that the state bucket didn't exist before it started.

Now the resource uses backends this doesn't seem to be possible - it's looking to write a lock file before it starts doing anything.

Any ideas on workarounds for this? It's especially tricky on GCP, where one needs to create not only a bucket but a project too. Maybe some option to run the `out` twice, first with a `local` backend and then the second time with the desired backend?

**Comment by ljfranklin** [comment]
Unfortunately this seems like a shortcoming in Terraform, would be nice if there was a first class solution to solving this problem. Not positive if this will work, but you might be able to do something like `put.params.backend_type: local` in a bootstrap job to create just the project and bucket, then run a second `put` with your normal backend config to create everything else. By default this would drop the local bootstrap state file on the floor which may or may not be acceptable for your use case. If not, you might be able to use `put.params.import_files` to pull the project and bucket IDs into your state file in the second `put`. I used the word "might" a few times because I haven't tried any of this but it seems like it could work. Good luck!

**Comment by DanielJonesEB** [comment]
Thanks for the thoughts! I ended up bodging together [a task to do it](https://github.com/EngineerBetter/concourse-gcp-tf-bootstrap) in the end. I'd tried the `put` with a local state backend, but it didn't work out (can't remember why).
